/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author leth4
 */
public class TelaMenu extends javax.swing.JFrame {

    /**
     * Creates new form TelaMenu
     */
    public TelaMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnFerramenta = new javax.swing.JButton();
        btnAmigo = new javax.swing.JButton();
        btnEmprestimo = new javax.swing.JButton();
        btnexit = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu");
        setUndecorated(true);
        getContentPane().setLayout(null);

        btnFerramenta.setBackground(new java.awt.Color(110, 13, 37));
        btnFerramenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/btnFerramentas.png"))); // NOI18N
        btnFerramenta.setContentAreaFilled(false);
        btnFerramenta.setFocusPainted(false);
        btnFerramenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFerramentaActionPerformed(evt);
            }
        });
        getContentPane().add(btnFerramenta);
        btnFerramenta.setBounds(380, 390, 270, 50);

        btnAmigo.setBackground(new java.awt.Color(110, 13, 37));
        btnAmigo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/botaoAmigo_1.png"))); // NOI18N
        btnAmigo.setContentAreaFilled(false);
        btnAmigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAmigoActionPerformed(evt);
            }
        });
        getContentPane().add(btnAmigo);
        btnAmigo.setBounds(380, 330, 270, 50);

        btnEmprestimo.setBackground(new java.awt.Color(110, 13, 37));
        btnEmprestimo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/btnEmprestimos.png"))); // NOI18N
        btnEmprestimo.setContentAreaFilled(false);
        btnEmprestimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmprestimoActionPerformed(evt);
            }
        });
        getContentPane().add(btnEmprestimo);
        btnEmprestimo.setBounds(380, 450, 270, 50);

        btnexit.setBackground(new java.awt.Color(110, 13, 37));
        btnexit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/btnexit.png"))); // NOI18N
        btnexit.setBorderPainted(false);
        btnexit.setContentAreaFilled(false);
        btnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexitActionPerformed(evt);
            }
        });
        getContentPane().add(btnexit);
        btnexit.setBounds(1010, 20, 50, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/welcome 2 (1).png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 1090, 640);

        setSize(new java.awt.Dimension(1080, 640));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAmigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAmigoActionPerformed
        new TelaAmigos().setVisible(true);
    }//GEN-LAST:event_btnAmigoActionPerformed

    private void btnFerramentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFerramentaActionPerformed
        new TelaFerramentas().setVisible(true);
    }//GEN-LAST:event_btnFerramentaActionPerformed

    private void btnEmprestimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmprestimoActionPerformed
        new TelaEmprestimos().setVisible(true);
    }//GEN-LAST:event_btnEmprestimoActionPerformed

    private void btnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnexitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAmigo;
    private javax.swing.JButton btnEmprestimo;
    private javax.swing.JButton btnFerramenta;
    private javax.swing.JButton btnexit;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
